name: login_tutorial
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  equatable: ^2.0.5
  flutter_easyloading: ^3.0.5
  flutter_screenutil: ^5.8.2
  adaptive_theme: ^3.2.1
  injectable: ^2.1.1
  freezed: ^2.3.4
  freezed_annotation: ^2.2.0
  get_it: ^7.6.0
  widget_and_text_animator: ^1.0.9
  firebase_core: ^2.16.0
  firebase_storage: ^11.2.7
  cloud_firestore: ^4.9.2
  awesome_dialog: ^3.1.0
  firebase_messaging: ^14.6.8
  firebase_auth: ^4.10.0
  google_sign_in: ^6.1.5

  cupertino_icons: ^1.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.4
  injectable_generator: ^2.1.5

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/appLoaderBg.png